window.SOLAR_WEATHER_DATA = {
  "meta": {
    "generated_at": "2026-09-28T19:20:03",
    "dataset": "Météo-France - Données climatologiques de base quotidiennes",
    "dataset_url": "https://www.data.gouv.fr/datasets/donnees-climatologiques-de-base-quotidiennes",
    "station_dataset_url": "https://www.data.gouv.fr/datasets/informations-sur-les-stations-meteo-france-metadonnees",
    "department": "81",
    "station_id": "81284001",
    "first_date": "2023-01-01",
    "latest_date": "2026-09-26",
    "baseline_period": "1991-2020",
    "source_resources": [
      {
        "title": "QUOT_departement_81_periode_1950-2024_RR-T-Vent",
        "url": "https://meteofrance.s3.sbg.io.cloud.ovh.net/data/synchro_ftp/BASE/QUOT/Q_81_previous-1950-2024_RR-T-Vent.csv.gz",
        "period": "1950-2024"
      },
      {
        "title": "QUOT_departement_81_periode_2025-2026_RR-T-Vent",
        "url": "https://meteofrance.s3.sbg.io.cloud.ovh.net/data/synchro_ftp/BASE/QUOT/Q_81_latest-2025-2026_RR-T-Vent.csv.gz",
        "period": "2025-2026"
      }
    ],
    "thresholds": {
      "hot_day_c": 30.0,
      "very_hot_day_c": 35.0,
      "tropical_night_c": 20.0,
      "frost_day_c": 0.0,
      "hard_frost_day_c": -5.0,
      "rain_day_mm": 1.0,
      "heavy_rain_mm": 20.0,
      "wind_gust_kmh": 60.0,
      "estimated_hot_sequence_min_days": 3
    },
    "note": "Les séquences chaudes sont un indicateur local estimé, pas une déclaration officielle de canicule."
  },
  "station": {
    "id": "81284001",
    "name": "ALBI",
    "long_name": "LE SEQUESTRE (ALBI)",
    "named_place": "AERODROME D'ALBI",
    "lat": 43.914667,
    "lon": 2.116333,
    "alt_m": 172.0,
    "start_date": "1976-11-01",
    "end_date": null,
    "is_open": true,
    "is_daily": true,
    "source_url": "https://static.data.gouv.fr/resources/stations-meteo-france/20250104-124154/stations-meteo-france.csv"
  },
  "normals": {
    "period": "1991-2020",
    "year_count": 30,
    "annual": {
      "avg_tx_c": 19.1,
      "avg_tn_c": 8.5,
      "avg_tm_c": 13.4,
      "hot_days_30": 40.4,
      "very_hot_days_35": 6.8,
      "tropical_nights_20": 7.2,
      "frost_days": 38.5,
      "hard_frost_days": 5.3,
      "ice_days": 1.3,
      "rain_total_mm": 733.8,
      "rain_days_1mm": 103.9,
      "heavy_rain_days_20mm": 6.1,
      "longest_dry_spell_days": 24.1,
      "windy_days_60kmh": 17.5,
      "estimated_hot_sequence_days": 27.7
    }
  },
  "years": [
    {
      "year": 2023,
      "month": null,
      "label": null,
      "filled_days": 365,
      "expected_days": 365,
      "coverage_percent": 100.0,
      "avg_tx_c": 20.8,
      "avg_tn_c": 9.5,
      "avg_tm_c": 14.6,
      "max_tx_c": 42.3,
      "max_tx_date": "2023-08-23",
      "min_tn_c": -5.5,
      "min_tn_date": "2023-03-01",
      "hot_days_30": 64,
      "very_hot_days_35": 13,
      "tropical_nights_20": 19,
      "frost_days": 43,
      "hard_frost_days": 2,
      "ice_days": 0,
      "rain_total_mm": 785.0,
      "rain_days_1mm": 110,
      "heavy_rain_days_20mm": 6,
      "wettest_day_mm": 42.5,
      "wettest_day_date": "2023-06-29",
      "longest_dry_spell_days": 32,
      "longest_dry_spell_start": "2023-01-20",
      "longest_dry_spell_end": "2023-02-20",
      "wind_gust_max_kmh": 90.0,
      "wind_gust_max_date": "2023-03-26",
      "windy_days_60kmh": 17,
      "estimated_hot_sequence_days": 48,
      "estimated_hot_sequence_episodes": 6,
      "longest_hot_sequence_days": 17,
      "hot_sequences": [
        {
          "start": "2023-07-06",
          "end": "2023-07-11",
          "days": 6,
          "max_tx_c": 35.4
        },
        {
          "start": "2023-07-27",
          "end": "2023-07-29",
          "days": 3,
          "max_tx_c": 33.7
        },
        {
          "start": "2023-08-08",
          "end": "2023-08-24",
          "days": 17,
          "max_tx_c": 42.3
        },
        {
          "start": "2023-09-03",
          "end": "2023-09-11",
          "days": 9,
          "max_tx_c": 35.2
        },
        {
          "start": "2023-09-27",
          "end": "2023-10-02",
          "days": 6,
          "max_tx_c": 34.3
        }
      ],
      "avg_tx_delta_c": 1.7,
      "hot_days_30_delta": 23.6,
      "very_hot_days_35_delta": 6.2,
      "frost_days_delta": 4.5,
      "rain_total_delta_mm": 51.2,
      "rain_days_1mm_delta": 6.1,
      "heavy_rain_days_20mm_delta": -0.1,
      "longest_dry_spell_delta_days": 7.9,
      "rain_total_delta_percent": 7.0,
      "status": "Année complète",
      "months": [
        {
          "year": null,
          "month": 1,
          "label": "Janvier",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 8.3,
          "avg_tn_c": 2.1,
          "avg_tm_c": 4.9,
          "max_tx_c": 17.6,
          "max_tx_date": "2023-01-01",
          "min_tn_c": -5.2,
          "min_tn_date": "2023-01-25",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 7,
          "hard_frost_days": 1,
          "ice_days": 0,
          "rain_total_mm": 80.8,
          "rain_days_1mm": 9,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 29.1,
          "wettest_day_date": "2023-01-17",
          "longest_dry_spell_days": 12,
          "longest_dry_spell_start": "2023-01-20",
          "longest_dry_spell_end": "2023-01-31",
          "wind_gust_max_kmh": 66.0,
          "wind_gust_max_date": "2023-01-17",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 2,
          "label": "Février",
          "filled_days": 28,
          "expected_days": 28,
          "coverage_percent": 100.0,
          "avg_tx_c": 12.9,
          "avg_tn_c": -0.4,
          "avg_tm_c": 5.6,
          "max_tx_c": 20.5,
          "max_tx_date": "2023-02-20",
          "min_tn_c": -4.5,
          "min_tn_date": "2023-02-10",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 19,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 18.3,
          "rain_days_1mm": 4,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 7.5,
          "wettest_day_date": "2023-02-23",
          "longest_dry_spell_days": 20,
          "longest_dry_spell_start": "2023-02-01",
          "longest_dry_spell_end": "2023-02-20",
          "wind_gust_max_kmh": 62.0,
          "wind_gust_max_date": "2023-02-26",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 3,
          "label": "Mars",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 16.7,
          "avg_tn_c": 5.3,
          "avg_tm_c": 10.3,
          "max_tx_c": 26.9,
          "max_tx_date": "2023-03-29",
          "min_tn_c": -5.5,
          "min_tn_date": "2023-03-01",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 5,
          "hard_frost_days": 1,
          "ice_days": 0,
          "rain_total_mm": 95.9,
          "rain_days_1mm": 10,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 20.8,
          "wettest_day_date": "2023-03-10",
          "longest_dry_spell_days": 6,
          "longest_dry_spell_start": "2023-03-01",
          "longest_dry_spell_end": "2023-03-06",
          "wind_gust_max_kmh": 90.0,
          "wind_gust_max_date": "2023-03-26",
          "windy_days_60kmh": 6,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 4,
          "label": "Avril",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 18.9,
          "avg_tn_c": 7.1,
          "avg_tm_c": 12.6,
          "max_tx_c": 28.7,
          "max_tx_date": "2023-04-28",
          "min_tn_c": -1.0,
          "min_tn_date": "2023-04-05",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 2,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 54.3,
          "rain_days_1mm": 10,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 7.8,
          "wettest_day_date": "2023-04-14",
          "longest_dry_spell_days": 10,
          "longest_dry_spell_start": "2023-04-02",
          "longest_dry_spell_end": "2023-04-11",
          "wind_gust_max_kmh": 73.0,
          "wind_gust_max_date": "2023-04-01",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 5,
          "label": "Mai",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 22.7,
          "avg_tn_c": 11.6,
          "avg_tm_c": 16.5,
          "max_tx_c": 30.7,
          "max_tx_date": "2023-05-27",
          "min_tn_c": 6.5,
          "min_tn_date": "2023-05-17",
          "hot_days_30": 3,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 85.6,
          "rain_days_1mm": 11,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 16.6,
          "wettest_day_date": "2023-05-13",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2023-05-22",
          "longest_dry_spell_end": "2023-05-28",
          "wind_gust_max_kmh": 52.0,
          "wind_gust_max_date": "2023-05-11",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 6,
          "label": "Juin",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 28.0,
          "avg_tn_c": 16.2,
          "avg_tm_c": 21.9,
          "max_tx_c": 33.2,
          "max_tx_date": "2023-06-25",
          "min_tn_c": 12.6,
          "min_tn_date": "2023-06-04",
          "hot_days_30": 4,
          "very_hot_days_35": 0,
          "tropical_nights_20": 1,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 96.7,
          "rain_days_1mm": 10,
          "heavy_rain_days_20mm": 2,
          "wettest_day_mm": 42.5,
          "wettest_day_date": "2023-06-29",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2023-06-10",
          "longest_dry_spell_end": "2023-06-16",
          "wind_gust_max_kmh": 51.0,
          "wind_gust_max_date": "2023-06-30",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 7,
          "label": "Juillet",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 30.1,
          "avg_tn_c": 17.5,
          "avg_tm_c": 23.6,
          "max_tx_c": 38.2,
          "max_tx_date": "2023-07-18",
          "min_tn_c": 13.0,
          "min_tn_date": "2023-07-14",
          "hot_days_30": 14,
          "very_hot_days_35": 4,
          "tropical_nights_20": 7,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 20.3,
          "rain_days_1mm": 6,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 7.8,
          "wettest_day_date": "2023-07-01",
          "longest_dry_spell_days": 8,
          "longest_dry_spell_start": "2023-07-24",
          "longest_dry_spell_end": "2023-07-31",
          "wind_gust_max_kmh": 61.0,
          "wind_gust_max_date": "2023-07-07",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 9,
          "estimated_hot_sequence_episodes": 2,
          "longest_hot_sequence_days": 6,
          "hot_sequences": [
            {
              "start": "2023-07-06",
              "end": "2023-07-11",
              "days": 6,
              "max_tx_c": 35.4
            },
            {
              "start": "2023-07-27",
              "end": "2023-07-29",
              "days": 3,
              "max_tx_c": 33.7
            }
          ]
        },
        {
          "year": null,
          "month": 8,
          "label": "Août",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 31.3,
          "avg_tn_c": 17.6,
          "avg_tm_c": 24.0,
          "max_tx_c": 42.3,
          "max_tx_date": "2023-08-23",
          "min_tn_c": 9.6,
          "min_tn_date": "2023-08-07",
          "hot_days_30": 18,
          "very_hot_days_35": 8,
          "tropical_nights_20": 10,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 38.5,
          "rain_days_1mm": 5,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 28.7,
          "wettest_day_date": "2023-08-26",
          "longest_dry_spell_days": 21,
          "longest_dry_spell_start": "2023-08-05",
          "longest_dry_spell_end": "2023-08-25",
          "wind_gust_max_kmh": 58.0,
          "wind_gust_max_date": "2023-08-03",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 17,
          "estimated_hot_sequence_episodes": 1,
          "longest_hot_sequence_days": 17,
          "hot_sequences": [
            {
              "start": "2023-08-08",
              "end": "2023-08-24",
              "days": 17,
              "max_tx_c": 42.3
            }
          ]
        },
        {
          "year": null,
          "month": 9,
          "label": "Septembre",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 29.7,
          "avg_tn_c": 15.2,
          "avg_tm_c": 21.8,
          "max_tx_c": 35.2,
          "max_tx_date": "2023-09-10",
          "min_tn_c": 7.1,
          "min_tn_date": "2023-09-24",
          "hot_days_30": 16,
          "very_hot_days_35": 1,
          "tropical_nights_20": 1,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 36.6,
          "rain_days_1mm": 5,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 17.4,
          "wettest_day_date": "2023-09-12",
          "longest_dry_spell_days": 10,
          "longest_dry_spell_start": "2023-09-02",
          "longest_dry_spell_end": "2023-09-11",
          "wind_gust_max_kmh": 62.0,
          "wind_gust_max_date": "2023-09-21",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 13,
          "estimated_hot_sequence_episodes": 2,
          "longest_hot_sequence_days": 9,
          "hot_sequences": [
            {
              "start": "2023-09-03",
              "end": "2023-09-11",
              "days": 9,
              "max_tx_c": 35.2
            },
            {
              "start": "2023-09-27",
              "end": "2023-09-30",
              "days": 4,
              "max_tx_c": 32.8
            }
          ]
        },
        {
          "year": null,
          "month": 10,
          "label": "Octobre",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 24.8,
          "avg_tn_c": 11.4,
          "avg_tm_c": 17.2,
          "max_tx_c": 34.3,
          "max_tx_date": "2023-10-01",
          "min_tn_c": 5.7,
          "min_tn_date": "2023-10-22",
          "hot_days_30": 9,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 51.6,
          "rain_days_1mm": 8,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 13.8,
          "wettest_day_date": "2023-10-26",
          "longest_dry_spell_days": 18,
          "longest_dry_spell_start": "2023-10-01",
          "longest_dry_spell_end": "2023-10-18",
          "wind_gust_max_kmh": 81.0,
          "wind_gust_max_date": "2023-10-23",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 7,
          "estimated_hot_sequence_episodes": 1,
          "longest_hot_sequence_days": 7,
          "hot_sequences": [
            {
              "start": "2023-10-07",
              "end": "2023-10-13",
              "days": 7,
              "max_tx_c": 32.3
            }
          ]
        },
        {
          "year": null,
          "month": 11,
          "label": "Novembre",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 14.4,
          "avg_tn_c": 5.7,
          "avg_tm_c": 9.6,
          "max_tx_c": 23.2,
          "max_tx_date": "2023-11-14",
          "min_tn_c": -4.1,
          "min_tn_date": "2023-11-26",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 3,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 118.8,
          "rain_days_1mm": 17,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 21.2,
          "wettest_day_date": "2023-11-02",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2023-11-13",
          "longest_dry_spell_end": "2023-11-19",
          "wind_gust_max_kmh": 63.0,
          "wind_gust_max_date": "2023-11-05",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 12,
          "label": "Décembre",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 11.4,
          "avg_tn_c": 3.6,
          "avg_tm_c": 6.9,
          "max_tx_c": 16.7,
          "max_tx_date": "2023-12-11",
          "min_tn_c": -4.9,
          "min_tn_date": "2023-12-03",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 7,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 87.6,
          "rain_days_1mm": 15,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 17.5,
          "wettest_day_date": "2023-12-07",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2023-12-24",
          "longest_dry_spell_end": "2023-12-30",
          "wind_gust_max_kmh": 58.0,
          "wind_gust_max_date": "2023-12-22",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        }
      ],
      "events": [
        {
          "type": "heat",
          "label": "Pic de chaleur",
          "value": "42.3 °C",
          "date": "2023-08-23"
        },
        {
          "type": "cold",
          "label": "Nuit la plus froide",
          "value": "-5.5 °C",
          "date": "2023-03-01"
        },
        {
          "type": "rain",
          "label": "Pluie la plus forte",
          "value": "42.5 mm",
          "date": "2023-06-29"
        },
        {
          "type": "dry",
          "label": "Plus longue période sèche",
          "value": "32 jours",
          "date": "2023-01-20",
          "end_date": "2023-02-20"
        },
        {
          "type": "wind",
          "label": "Rafale maximale",
          "value": "90 km/h",
          "date": "2023-03-26"
        }
      ]
    },
    {
      "year": 2024,
      "month": null,
      "label": null,
      "filled_days": 366,
      "expected_days": 366,
      "coverage_percent": 100.0,
      "avg_tx_c": 20.1,
      "avg_tn_c": 9.6,
      "avg_tm_c": 14.3,
      "max_tx_c": 38.3,
      "max_tx_date": "2024-07-29",
      "min_tn_c": -6.7,
      "min_tn_date": "2024-01-20",
      "hot_days_30": 46,
      "very_hot_days_35": 9,
      "tropical_nights_20": 15,
      "frost_days": 23,
      "hard_frost_days": 1,
      "ice_days": 0,
      "rain_total_mm": 823.5,
      "rain_days_1mm": 109,
      "heavy_rain_days_20mm": 8,
      "wettest_day_mm": 43.0,
      "wettest_day_date": "2024-10-17",
      "longest_dry_spell_days": 21,
      "longest_dry_spell_start": "2024-01-19",
      "longest_dry_spell_end": "2024-02-08",
      "wind_gust_max_kmh": 98.0,
      "wind_gust_max_date": "2024-04-27",
      "windy_days_60kmh": 23,
      "estimated_hot_sequence_days": 35,
      "estimated_hot_sequence_episodes": 6,
      "longest_hot_sequence_days": 10,
      "hot_sequences": [
        {
          "start": "2024-06-25",
          "end": "2024-06-28",
          "days": 4,
          "max_tx_c": 33.2
        },
        {
          "start": "2024-07-08",
          "end": "2024-07-11",
          "days": 4,
          "max_tx_c": 35.7
        },
        {
          "start": "2024-07-18",
          "end": "2024-07-20",
          "days": 3,
          "max_tx_c": 35.6
        },
        {
          "start": "2024-07-23",
          "end": "2024-07-31",
          "days": 9,
          "max_tx_c": 38.3
        },
        {
          "start": "2024-08-04",
          "end": "2024-08-13",
          "days": 10,
          "max_tx_c": 37.2
        }
      ],
      "avg_tx_delta_c": 1.0,
      "hot_days_30_delta": 5.6,
      "very_hot_days_35_delta": 2.2,
      "frost_days_delta": -15.5,
      "rain_total_delta_mm": 89.7,
      "rain_days_1mm_delta": 5.1,
      "heavy_rain_days_20mm_delta": 1.9,
      "longest_dry_spell_delta_days": -3.1,
      "rain_total_delta_percent": 12.2,
      "status": "Année complète",
      "months": [
        {
          "year": null,
          "month": 1,
          "label": "Janvier",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 11.2,
          "avg_tn_c": 2.7,
          "avg_tm_c": 6.4,
          "max_tx_c": 18.6,
          "max_tx_date": "2024-01-25",
          "min_tn_c": -6.7,
          "min_tn_date": "2024-01-20",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 8,
          "hard_frost_days": 1,
          "ice_days": 0,
          "rain_total_mm": 33.5,
          "rain_days_1mm": 7,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 10.7,
          "wettest_day_date": "2024-01-10",
          "longest_dry_spell_days": 13,
          "longest_dry_spell_start": "2024-01-19",
          "longest_dry_spell_end": "2024-01-31",
          "wind_gust_max_kmh": 53.0,
          "wind_gust_max_date": "2024-01-18",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 2,
          "label": "Février",
          "filled_days": 29,
          "expected_days": 29,
          "coverage_percent": 100.0,
          "avg_tx_c": 13.2,
          "avg_tn_c": 5.6,
          "avg_tm_c": 8.9,
          "max_tx_c": 20.4,
          "max_tx_date": "2024-02-14",
          "min_tn_c": -1.0,
          "min_tn_date": "2024-02-29",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 1,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 83.6,
          "rain_days_1mm": 11,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 21.8,
          "wettest_day_date": "2024-02-25",
          "longest_dry_spell_days": 8,
          "longest_dry_spell_start": "2024-02-01",
          "longest_dry_spell_end": "2024-02-08",
          "wind_gust_max_kmh": 89.0,
          "wind_gust_max_date": "2024-02-22",
          "windy_days_60kmh": 3,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 3,
          "label": "Mars",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 17.1,
          "avg_tn_c": 6.4,
          "avg_tm_c": 11.4,
          "max_tx_c": 24.9,
          "max_tx_date": "2024-03-22",
          "min_tn_c": 1.3,
          "min_tn_date": "2024-03-04",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 58.0,
          "rain_days_1mm": 12,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 11.1,
          "wettest_day_date": "2024-03-02",
          "longest_dry_spell_days": 8,
          "longest_dry_spell_start": "2024-03-18",
          "longest_dry_spell_end": "2024-03-25",
          "wind_gust_max_kmh": 68.0,
          "wind_gust_max_date": "2024-03-09",
          "windy_days_60kmh": 4,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 4,
          "label": "Avril",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 19.0,
          "avg_tn_c": 7.3,
          "avg_tm_c": 12.8,
          "max_tx_c": 30.1,
          "max_tx_date": "2024-04-14",
          "min_tn_c": -0.4,
          "min_tn_date": "2024-04-19",
          "hot_days_30": 1,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 3,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 67.6,
          "rain_days_1mm": 8,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 21.0,
          "wettest_day_date": "2024-04-08",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2024-04-10",
          "longest_dry_spell_end": "2024-04-16",
          "wind_gust_max_kmh": 98.0,
          "wind_gust_max_date": "2024-04-27",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 5,
          "label": "Mai",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 21.3,
          "avg_tn_c": 10.7,
          "avg_tm_c": 15.5,
          "max_tx_c": 28.1,
          "max_tx_date": "2024-05-10",
          "min_tn_c": 3.4,
          "min_tn_date": "2024-05-03",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 124.3,
          "rain_days_1mm": 16,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 31.9,
          "wettest_day_date": "2024-05-01",
          "longest_dry_spell_days": 5,
          "longest_dry_spell_start": "2024-05-08",
          "longest_dry_spell_end": "2024-05-12",
          "wind_gust_max_kmh": 64.0,
          "wind_gust_max_date": "2024-05-02",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 6,
          "label": "Juin",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 26.3,
          "avg_tn_c": 14.8,
          "avg_tm_c": 20.2,
          "max_tx_c": 33.2,
          "max_tx_date": "2024-06-26",
          "min_tn_c": 8.4,
          "min_tn_date": "2024-06-13",
          "hot_days_30": 7,
          "very_hot_days_35": 0,
          "tropical_nights_20": 2,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 80.4,
          "rain_days_1mm": 6,
          "heavy_rain_days_20mm": 2,
          "wettest_day_mm": 24.6,
          "wettest_day_date": "2024-06-29",
          "longest_dry_spell_days": 12,
          "longest_dry_spell_start": "2024-06-02",
          "longest_dry_spell_end": "2024-06-13",
          "wind_gust_max_kmh": 71.0,
          "wind_gust_max_date": "2024-06-29",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 4,
          "estimated_hot_sequence_episodes": 1,
          "longest_hot_sequence_days": 4,
          "hot_sequences": [
            {
              "start": "2024-06-25",
              "end": "2024-06-28",
              "days": 4,
              "max_tx_c": 33.2
            }
          ]
        },
        {
          "year": null,
          "month": 7,
          "label": "Juillet",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 29.9,
          "avg_tn_c": 17.1,
          "avg_tm_c": 23.4,
          "max_tx_c": 38.3,
          "max_tx_date": "2024-07-29",
          "min_tn_c": 11.0,
          "min_tn_date": "2024-07-13",
          "hot_days_30": 19,
          "very_hot_days_35": 6,
          "tropical_nights_20": 7,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 59.3,
          "rain_days_1mm": 8,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 19.9,
          "wettest_day_date": "2024-07-09",
          "longest_dry_spell_days": 11,
          "longest_dry_spell_start": "2024-07-21",
          "longest_dry_spell_end": "2024-07-31",
          "wind_gust_max_kmh": 55.0,
          "wind_gust_max_date": "2024-07-21",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 16,
          "estimated_hot_sequence_episodes": 3,
          "longest_hot_sequence_days": 9,
          "hot_sequences": [
            {
              "start": "2024-07-08",
              "end": "2024-07-11",
              "days": 4,
              "max_tx_c": 35.7
            },
            {
              "start": "2024-07-18",
              "end": "2024-07-20",
              "days": 3,
              "max_tx_c": 35.6
            },
            {
              "start": "2024-07-23",
              "end": "2024-07-31",
              "days": 9,
              "max_tx_c": 38.3
            }
          ]
        },
        {
          "year": null,
          "month": 8,
          "label": "Août",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 30.5,
          "avg_tn_c": 17.2,
          "avg_tm_c": 23.4,
          "max_tx_c": 37.2,
          "max_tx_date": "2024-08-11",
          "min_tn_c": 10.9,
          "min_tn_date": "2024-08-27",
          "hot_days_30": 18,
          "very_hot_days_35": 3,
          "tropical_nights_20": 5,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 45.7,
          "rain_days_1mm": 3,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 30.2,
          "wettest_day_date": "2024-08-24",
          "longest_dry_spell_days": 9,
          "longest_dry_spell_start": "2024-08-15",
          "longest_dry_spell_end": "2024-08-23",
          "wind_gust_max_kmh": 75.0,
          "wind_gust_max_date": "2024-08-24",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 15,
          "estimated_hot_sequence_episodes": 2,
          "longest_hot_sequence_days": 10,
          "hot_sequences": [
            {
              "start": "2024-08-04",
              "end": "2024-08-13",
              "days": 10,
              "max_tx_c": 37.2
            },
            {
              "start": "2024-08-27",
              "end": "2024-08-31",
              "days": 5,
              "max_tx_c": 33.3
            }
          ]
        },
        {
          "year": null,
          "month": 9,
          "label": "Septembre",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 22.8,
          "avg_tn_c": 12.3,
          "avg_tm_c": 16.9,
          "max_tx_c": 30.6,
          "max_tx_date": "2024-09-02",
          "min_tn_c": 4.0,
          "min_tn_date": "2024-09-29",
          "hot_days_30": 1,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 77.7,
          "rain_days_1mm": 11,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 22.2,
          "wettest_day_date": "2024-09-04",
          "longest_dry_spell_days": 9,
          "longest_dry_spell_start": "2024-09-12",
          "longest_dry_spell_end": "2024-09-20",
          "wind_gust_max_kmh": 55.0,
          "wind_gust_max_date": "2024-09-21",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 10,
          "label": "Octobre",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 21.7,
          "avg_tn_c": 11.9,
          "avg_tm_c": 16.2,
          "max_tx_c": 28.9,
          "max_tx_date": "2024-10-09",
          "min_tn_c": 5.1,
          "min_tn_date": "2024-10-05",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 1,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 106.3,
          "rain_days_1mm": 11,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 43.0,
          "wettest_day_date": "2024-10-17",
          "longest_dry_spell_days": 6,
          "longest_dry_spell_start": "2024-10-11",
          "longest_dry_spell_end": "2024-10-16",
          "wind_gust_max_kmh": 67.0,
          "wind_gust_max_date": "2024-10-15",
          "windy_days_60kmh": 3,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 11,
          "label": "Novembre",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 17.4,
          "avg_tn_c": 6.6,
          "avg_tm_c": 11.1,
          "max_tx_c": 24.8,
          "max_tx_date": "2024-11-01",
          "min_tn_c": -1.0,
          "min_tn_date": "2024-11-23",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 1,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 39.1,
          "rain_days_1mm": 5,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 10.6,
          "wettest_day_date": "2024-11-20",
          "longest_dry_spell_days": 11,
          "longest_dry_spell_start": "2024-11-01",
          "longest_dry_spell_end": "2024-11-11",
          "wind_gust_max_kmh": 76.0,
          "wind_gust_max_date": "2024-11-21",
          "windy_days_60kmh": 4,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 12,
          "label": "Décembre",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 10.3,
          "avg_tn_c": 2.3,
          "avg_tm_c": 5.6,
          "max_tx_c": 17.1,
          "max_tx_date": "2024-12-18",
          "min_tn_c": -2.9,
          "min_tn_date": "2024-12-28",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 10,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 48.0,
          "rain_days_1mm": 11,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 10.0,
          "wettest_day_date": "2024-12-21",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2024-12-25",
          "longest_dry_spell_end": "2024-12-31",
          "wind_gust_max_kmh": 75.0,
          "wind_gust_max_date": "2024-12-22",
          "windy_days_60kmh": 3,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        }
      ],
      "events": [
        {
          "type": "heat",
          "label": "Pic de chaleur",
          "value": "38.3 °C",
          "date": "2024-07-29"
        },
        {
          "type": "cold",
          "label": "Nuit la plus froide",
          "value": "-6.7 °C",
          "date": "2024-01-20"
        },
        {
          "type": "rain",
          "label": "Pluie la plus forte",
          "value": "43.0 mm",
          "date": "2024-10-17"
        },
        {
          "type": "dry",
          "label": "Plus longue période sèche",
          "value": "21 jours",
          "date": "2024-01-19",
          "end_date": "2024-02-08"
        },
        {
          "type": "wind",
          "label": "Rafale maximale",
          "value": "98 km/h",
          "date": "2024-04-27"
        }
      ]
    },
    {
      "year": 2025,
      "month": null,
      "label": null,
      "filled_days": 365,
      "expected_days": 365,
      "coverage_percent": 100.0,
      "avg_tx_c": 20.8,
      "avg_tn_c": 9.3,
      "avg_tm_c": 14.6,
      "max_tx_c": 41.3,
      "max_tx_date": "2025-08-11",
      "min_tn_c": -6.8,
      "min_tn_date": "2025-01-14",
      "hot_days_30": 54,
      "very_hot_days_35": 22,
      "tropical_nights_20": 18,
      "frost_days": 33,
      "hard_frost_days": 3,
      "ice_days": 1,
      "rain_total_mm": 829.2,
      "rain_days_1mm": 90,
      "heavy_rain_days_20mm": 9,
      "wettest_day_mm": 52.8,
      "wettest_day_date": "2025-11-06",
      "longest_dry_spell_days": 21,
      "longest_dry_spell_start": "2025-06-15",
      "longest_dry_spell_end": "2025-07-05",
      "wind_gust_max_kmh": 91.0,
      "wind_gust_max_date": "2025-03-09",
      "windy_days_60kmh": 25,
      "estimated_hot_sequence_days": 44,
      "estimated_hot_sequence_episodes": 7,
      "longest_hot_sequence_days": 14,
      "hot_sequences": [
        {
          "start": "2025-06-10",
          "end": "2025-06-13",
          "days": 4,
          "max_tx_c": 35.8
        },
        {
          "start": "2025-06-17",
          "end": "2025-06-25",
          "days": 9,
          "max_tx_c": 37.3
        },
        {
          "start": "2025-06-27",
          "end": "2025-07-01",
          "days": 5,
          "max_tx_c": 39.0
        },
        {
          "start": "2025-07-03",
          "end": "2025-07-05",
          "days": 3,
          "max_tx_c": 34.5
        },
        {
          "start": "2025-07-09",
          "end": "2025-07-14",
          "days": 6,
          "max_tx_c": 35.1
        }
      ],
      "avg_tx_delta_c": 1.7,
      "hot_days_30_delta": 13.6,
      "very_hot_days_35_delta": 15.2,
      "frost_days_delta": -5.5,
      "rain_total_delta_mm": 95.4,
      "rain_days_1mm_delta": -13.9,
      "heavy_rain_days_20mm_delta": 2.9,
      "longest_dry_spell_delta_days": -3.1,
      "rain_total_delta_percent": 13.0,
      "status": "Année complète",
      "months": [
        {
          "year": null,
          "month": 1,
          "label": "Janvier",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 11.6,
          "avg_tn_c": 1.4,
          "avg_tm_c": 5.9,
          "max_tx_c": 18.1,
          "max_tx_date": "2025-01-08",
          "min_tn_c": -6.8,
          "min_tn_date": "2025-01-14",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 12,
          "hard_frost_days": 3,
          "ice_days": 1,
          "rain_total_mm": 61.9,
          "rain_days_1mm": 11,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 15.0,
          "wettest_day_date": "2025-01-27",
          "longest_dry_spell_days": 10,
          "longest_dry_spell_start": "2025-01-11",
          "longest_dry_spell_end": "2025-01-20",
          "wind_gust_max_kmh": 64.0,
          "wind_gust_max_date": "2025-01-28",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 2,
          "label": "Février",
          "filled_days": 28,
          "expected_days": 28,
          "coverage_percent": 100.0,
          "avg_tx_c": 14.3,
          "avg_tn_c": 2.5,
          "avg_tm_c": 7.6,
          "max_tx_c": 20.5,
          "max_tx_date": "2025-02-20",
          "min_tn_c": -2.8,
          "min_tn_date": "2025-02-05",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 10,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 37.6,
          "rain_days_1mm": 4,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 28.2,
          "wettest_day_date": "2025-02-12",
          "longest_dry_spell_days": 9,
          "longest_dry_spell_start": "2025-02-13",
          "longest_dry_spell_end": "2025-02-21",
          "wind_gust_max_kmh": 77.0,
          "wind_gust_max_date": "2025-02-07",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 3,
          "label": "Mars",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 15.5,
          "avg_tn_c": 5.6,
          "avg_tm_c": 10.3,
          "max_tx_c": 20.1,
          "max_tx_date": "2025-03-31",
          "min_tn_c": -1.8,
          "min_tn_date": "2025-03-16",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 2,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 77.6,
          "rain_days_1mm": 7,
          "heavy_rain_days_20mm": 2,
          "wettest_day_mm": 21.7,
          "wettest_day_date": "2025-03-24",
          "longest_dry_spell_days": 8,
          "longest_dry_spell_start": "2025-03-01",
          "longest_dry_spell_end": "2025-03-08",
          "wind_gust_max_kmh": 91.0,
          "wind_gust_max_date": "2025-03-09",
          "windy_days_60kmh": 9,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 4,
          "label": "Avril",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 20.4,
          "avg_tn_c": 8.3,
          "avg_tm_c": 14.0,
          "max_tx_c": 25.0,
          "max_tx_date": "2025-04-10",
          "min_tn_c": 3.6,
          "min_tn_date": "2025-04-18",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 85.6,
          "rain_days_1mm": 8,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 29.3,
          "wettest_day_date": "2025-04-19",
          "longest_dry_spell_days": 12,
          "longest_dry_spell_start": "2025-04-01",
          "longest_dry_spell_end": "2025-04-12",
          "wind_gust_max_kmh": 89.0,
          "wind_gust_max_date": "2025-04-02",
          "windy_days_60kmh": 4,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 5,
          "label": "Mai",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 23.1,
          "avg_tn_c": 11.0,
          "avg_tm_c": 16.9,
          "max_tx_c": 34.1,
          "max_tx_date": "2025-05-30",
          "min_tn_c": 4.6,
          "min_tn_date": "2025-05-08",
          "hot_days_30": 2,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 134.8,
          "rain_days_1mm": 8,
          "heavy_rain_days_20mm": 2,
          "wettest_day_mm": 49.7,
          "wettest_day_date": "2025-05-19",
          "longest_dry_spell_days": 10,
          "longest_dry_spell_start": "2025-05-22",
          "longest_dry_spell_end": "2025-05-31",
          "wind_gust_max_kmh": 62.0,
          "wind_gust_max_date": "2025-05-19",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 6,
          "label": "Juin",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 30.7,
          "avg_tn_c": 17.0,
          "avg_tm_c": 23.7,
          "max_tx_c": 38.3,
          "max_tx_date": "2025-06-30",
          "min_tn_c": 10.8,
          "min_tn_date": "2025-06-09",
          "hot_days_30": 17,
          "very_hot_days_35": 7,
          "tropical_nights_20": 5,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 44.6,
          "rain_days_1mm": 6,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 15.5,
          "wettest_day_date": "2025-06-04",
          "longest_dry_spell_days": 16,
          "longest_dry_spell_start": "2025-06-15",
          "longest_dry_spell_end": "2025-06-30",
          "wind_gust_max_kmh": 73.0,
          "wind_gust_max_date": "2025-06-25",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 17,
          "estimated_hot_sequence_episodes": 3,
          "longest_hot_sequence_days": 9,
          "hot_sequences": [
            {
              "start": "2025-06-10",
              "end": "2025-06-13",
              "days": 4,
              "max_tx_c": 35.8
            },
            {
              "start": "2025-06-17",
              "end": "2025-06-25",
              "days": 9,
              "max_tx_c": 37.3
            },
            {
              "start": "2025-06-27",
              "end": "2025-06-30",
              "days": 4,
              "max_tx_c": 38.3
            }
          ]
        },
        {
          "year": null,
          "month": 7,
          "label": "Juillet",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 29.5,
          "avg_tn_c": 16.8,
          "avg_tm_c": 22.7,
          "max_tx_c": 39.0,
          "max_tx_date": "2025-07-01",
          "min_tn_c": 10.8,
          "min_tn_date": "2025-07-09",
          "hot_days_30": 14,
          "very_hot_days_35": 3,
          "tropical_nights_20": 4,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 39.4,
          "rain_days_1mm": 6,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 13.8,
          "wettest_day_date": "2025-07-20",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2025-07-13",
          "longest_dry_spell_end": "2025-07-19",
          "wind_gust_max_kmh": 69.0,
          "wind_gust_max_date": "2025-07-12",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 12,
          "estimated_hot_sequence_episodes": 3,
          "longest_hot_sequence_days": 6,
          "hot_sequences": [
            {
              "start": "2025-07-03",
              "end": "2025-07-05",
              "days": 3,
              "max_tx_c": 34.5
            },
            {
              "start": "2025-07-09",
              "end": "2025-07-14",
              "days": 6,
              "max_tx_c": 35.1
            },
            {
              "start": "2025-07-16",
              "end": "2025-07-18",
              "days": 3,
              "max_tx_c": 35.8
            }
          ]
        },
        {
          "year": null,
          "month": 8,
          "label": "Août",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 32.0,
          "avg_tn_c": 17.2,
          "avg_tm_c": 24.1,
          "max_tx_c": 41.3,
          "max_tx_date": "2025-08-11",
          "min_tn_c": 11.0,
          "min_tn_date": "2025-08-03",
          "hot_days_30": 17,
          "very_hot_days_35": 12,
          "tropical_nights_20": 9,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 87.1,
          "rain_days_1mm": 9,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 34.9,
          "wettest_day_date": "2025-08-27",
          "longest_dry_spell_days": 12,
          "longest_dry_spell_start": "2025-08-01",
          "longest_dry_spell_end": "2025-08-12",
          "wind_gust_max_kmh": 90.0,
          "wind_gust_max_date": "2025-08-13",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 14,
          "estimated_hot_sequence_episodes": 1,
          "longest_hot_sequence_days": 14,
          "hot_sequences": [
            {
              "start": "2025-08-04",
              "end": "2025-08-17",
              "days": 14,
              "max_tx_c": 41.3
            }
          ]
        },
        {
          "year": null,
          "month": 9,
          "label": "Septembre",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 23.8,
          "avg_tn_c": 12.8,
          "avg_tm_c": 17.7,
          "max_tx_c": 32.7,
          "max_tx_date": "2025-09-18",
          "min_tn_c": 5.5,
          "min_tn_date": "2025-09-27",
          "hot_days_30": 4,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 56.0,
          "rain_days_1mm": 6,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 19.0,
          "wettest_day_date": "2025-09-20",
          "longest_dry_spell_days": 9,
          "longest_dry_spell_start": "2025-09-11",
          "longest_dry_spell_end": "2025-09-19",
          "wind_gust_max_kmh": 57.0,
          "wind_gust_max_date": "2025-09-08",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 10,
          "label": "Octobre",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 21.1,
          "avg_tn_c": 9.1,
          "avg_tm_c": 14.3,
          "max_tx_c": 26.9,
          "max_tx_date": "2025-10-11",
          "min_tn_c": 3.5,
          "min_tn_date": "2025-10-06",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 57.7,
          "rain_days_1mm": 10,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 20.2,
          "wettest_day_date": "2025-10-22",
          "longest_dry_spell_days": 14,
          "longest_dry_spell_start": "2025-10-05",
          "longest_dry_spell_end": "2025-10-18",
          "wind_gust_max_kmh": 84.0,
          "wind_gust_max_date": "2025-10-23",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 11,
          "label": "Novembre",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 14.5,
          "avg_tn_c": 5.7,
          "avg_tm_c": 9.5,
          "max_tx_c": 23.0,
          "max_tx_date": "2025-11-12",
          "min_tn_c": -2.9,
          "min_tn_date": "2025-11-22",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 7,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 100.5,
          "rain_days_1mm": 8,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 52.8,
          "wettest_day_date": "2025-11-06",
          "longest_dry_spell_days": 8,
          "longest_dry_spell_start": "2025-11-09",
          "longest_dry_spell_end": "2025-11-16",
          "wind_gust_max_kmh": 88.0,
          "wind_gust_max_date": "2025-11-14",
          "windy_days_60kmh": 2,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 12,
          "label": "Décembre",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 12.7,
          "avg_tn_c": 4.2,
          "avg_tm_c": 7.9,
          "max_tx_c": 18.2,
          "max_tx_date": "2025-12-09",
          "min_tn_c": -1.5,
          "min_tn_date": "2025-12-31",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 2,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 46.4,
          "rain_days_1mm": 7,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 15.5,
          "wettest_day_date": "2025-12-22",
          "longest_dry_spell_days": 10,
          "longest_dry_spell_start": "2025-12-07",
          "longest_dry_spell_end": "2025-12-16",
          "wind_gust_max_kmh": 67.0,
          "wind_gust_max_date": "2025-12-15",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        }
      ],
      "events": [
        {
          "type": "heat",
          "label": "Pic de chaleur",
          "value": "41.3 °C",
          "date": "2025-08-11"
        },
        {
          "type": "cold",
          "label": "Nuit la plus froide",
          "value": "-6.8 °C",
          "date": "2025-01-14"
        },
        {
          "type": "rain",
          "label": "Pluie la plus forte",
          "value": "52.8 mm",
          "date": "2025-11-06"
        },
        {
          "type": "dry",
          "label": "Plus longue période sèche",
          "value": "21 jours",
          "date": "2025-06-15",
          "end_date": "2025-07-05"
        },
        {
          "type": "wind",
          "label": "Rafale maximale",
          "value": "91 km/h",
          "date": "2025-03-09"
        }
      ]
    },
    {
      "year": 2026,
      "month": null,
      "label": null,
      "filled_days": 269,
      "expected_days": 365,
      "coverage_percent": 73.7,
      "avg_tx_c": 24.3,
      "avg_tn_c": 11.3,
      "avg_tm_c": 17.5,
      "max_tx_c": 41.6,
      "max_tx_date": "2026-06-23",
      "min_tn_c": -8.2,
      "min_tn_date": "2026-01-05",
      "hot_days_30": 93,
      "very_hot_days_35": 47,
      "tropical_nights_20": 33,
      "frost_days": 9,
      "hard_frost_days": 2,
      "ice_days": 1,
      "rain_total_mm": 531.5,
      "rain_days_1mm": 64,
      "heavy_rain_days_20mm": 4,
      "wettest_day_mm": 42.9,
      "wettest_day_date": "2026-05-04",
      "longest_dry_spell_days": 26,
      "longest_dry_spell_start": "2026-06-29",
      "longest_dry_spell_end": "2026-07-24",
      "wind_gust_max_kmh": 113.0,
      "wind_gust_max_date": "2026-02-12",
      "windy_days_60kmh": 15,
      "estimated_hot_sequence_days": 90,
      "estimated_hot_sequence_episodes": 9,
      "longest_hot_sequence_days": 23,
      "hot_sequences": [
        {
          "start": "2026-05-21",
          "end": "2026-05-29",
          "days": 9,
          "max_tx_c": 34.6
        },
        {
          "start": "2026-06-13",
          "end": "2026-06-30",
          "days": 18,
          "max_tx_c": 41.6
        },
        {
          "start": "2026-07-02",
          "end": "2026-07-24",
          "days": 23,
          "max_tx_c": 40.3
        },
        {
          "start": "2026-07-28",
          "end": "2026-07-30",
          "days": 3,
          "max_tx_c": 41.5
        },
        {
          "start": "2026-08-01",
          "end": "2026-08-15",
          "days": 15,
          "max_tx_c": 39.9
        }
      ],
      "avg_tx_delta_c": 5.2,
      "hot_days_30_delta": 52.6,
      "very_hot_days_35_delta": 40.2,
      "frost_days_delta": -29.5,
      "rain_total_delta_mm": -202.3,
      "rain_days_1mm_delta": -39.9,
      "heavy_rain_days_20mm_delta": -2.1,
      "longest_dry_spell_delta_days": 1.9,
      "rain_total_delta_percent": -27.6,
      "status": "En cours",
      "months": [
        {
          "year": null,
          "month": 1,
          "label": "Janvier",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 9.5,
          "avg_tn_c": 2.0,
          "avg_tm_c": 5.4,
          "max_tx_c": 16.4,
          "max_tx_date": "2026-01-15",
          "min_tn_c": -8.2,
          "min_tn_date": "2026-01-05",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 8,
          "hard_frost_days": 2,
          "ice_days": 1,
          "rain_total_mm": 116.9,
          "rain_days_1mm": 15,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 16.2,
          "wettest_day_date": "2026-01-27",
          "longest_dry_spell_days": 8,
          "longest_dry_spell_start": "2026-01-10",
          "longest_dry_spell_end": "2026-01-17",
          "wind_gust_max_kmh": 65.0,
          "wind_gust_max_date": "2026-01-09",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 2,
          "label": "Février",
          "filled_days": 28,
          "expected_days": 28,
          "coverage_percent": 100.0,
          "avg_tx_c": 14.5,
          "avg_tn_c": 5.7,
          "avg_tm_c": 9.6,
          "max_tx_c": 23.9,
          "max_tx_date": "2026-02-24",
          "min_tn_c": 1.5,
          "min_tn_date": "2026-02-04",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 148.2,
          "rain_days_1mm": 14,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 26.4,
          "wettest_day_date": "2026-02-10",
          "longest_dry_spell_days": 8,
          "longest_dry_spell_start": "2026-02-20",
          "longest_dry_spell_end": "2026-02-27",
          "wind_gust_max_kmh": 113.0,
          "wind_gust_max_date": "2026-02-12",
          "windy_days_60kmh": 6,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 3,
          "label": "Mars",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 16.1,
          "avg_tn_c": 4.5,
          "avg_tm_c": 10.0,
          "max_tx_c": 23.3,
          "max_tx_date": "2026-03-17",
          "min_tn_c": -0.6,
          "min_tn_date": "2026-03-16",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 1,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 40.1,
          "rain_days_1mm": 10,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 16.5,
          "wettest_day_date": "2026-03-13",
          "longest_dry_spell_days": 7,
          "longest_dry_spell_start": "2026-03-15",
          "longest_dry_spell_end": "2026-03-21",
          "wind_gust_max_kmh": 59.0,
          "wind_gust_max_date": "2026-03-25",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 4,
          "label": "Avril",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 22.7,
          "avg_tn_c": 8.3,
          "avg_tm_c": 15.3,
          "max_tx_c": 29.8,
          "max_tx_date": "2026-04-06",
          "min_tn_c": 2.1,
          "min_tn_date": "2026-04-01",
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 34.8,
          "rain_days_1mm": 5,
          "heavy_rain_days_20mm": 1,
          "wettest_day_mm": 24.0,
          "wettest_day_date": "2026-04-12",
          "longest_dry_spell_days": 14,
          "longest_dry_spell_start": "2026-04-14",
          "longest_dry_spell_end": "2026-04-27",
          "wind_gust_max_kmh": 56.0,
          "wind_gust_max_date": "2026-04-01",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 5,
          "label": "Mai",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 24.7,
          "avg_tn_c": 12.2,
          "avg_tm_c": 18.2,
          "max_tx_c": 34.6,
          "max_tx_date": "2026-05-27",
          "min_tn_c": 6.2,
          "min_tn_date": "2026-05-16",
          "hot_days_30": 9,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 104.8,
          "rain_days_1mm": 7,
          "heavy_rain_days_20mm": 2,
          "wettest_day_mm": 42.9,
          "wettest_day_date": "2026-05-04",
          "longest_dry_spell_days": 16,
          "longest_dry_spell_start": "2026-05-16",
          "longest_dry_spell_end": "2026-05-31",
          "wind_gust_max_kmh": 62.0,
          "wind_gust_max_date": "2026-05-10",
          "windy_days_60kmh": 3,
          "estimated_hot_sequence_days": 9,
          "estimated_hot_sequence_episodes": 1,
          "longest_hot_sequence_days": 9,
          "hot_sequences": [
            {
              "start": "2026-05-21",
              "end": "2026-05-29",
              "days": 9,
              "max_tx_c": 34.6
            }
          ]
        },
        {
          "year": null,
          "month": 6,
          "label": "Juin",
          "filled_days": 30,
          "expected_days": 30,
          "coverage_percent": 100.0,
          "avg_tx_c": 31.8,
          "avg_tn_c": 16.9,
          "avg_tm_c": 24.3,
          "max_tx_c": 41.6,
          "max_tx_date": "2026-06-23",
          "min_tn_c": 10.5,
          "min_tn_date": "2026-06-10",
          "hot_days_30": 18,
          "very_hot_days_35": 11,
          "tropical_nights_20": 8,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 22.7,
          "rain_days_1mm": 3,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 16.7,
          "wettest_day_date": "2026-06-04",
          "longest_dry_spell_days": 23,
          "longest_dry_spell_start": "2026-06-05",
          "longest_dry_spell_end": "2026-06-27",
          "wind_gust_max_kmh": 67.0,
          "wind_gust_max_date": "2026-06-09",
          "windy_days_60kmh": 1,
          "estimated_hot_sequence_days": 18,
          "estimated_hot_sequence_episodes": 1,
          "longest_hot_sequence_days": 18,
          "hot_sequences": [
            {
              "start": "2026-06-13",
              "end": "2026-06-30",
              "days": 18,
              "max_tx_c": 41.6
            }
          ]
        },
        {
          "year": null,
          "month": 7,
          "label": "Juillet",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 35.5,
          "avg_tn_c": 19.3,
          "avg_tm_c": 27.3,
          "max_tx_c": 41.5,
          "max_tx_date": "2026-07-29",
          "min_tn_c": 15.0,
          "min_tn_date": "2026-07-28",
          "hot_days_30": 26,
          "very_hot_days_35": 20,
          "tropical_nights_20": 14,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 11.5,
          "rain_days_1mm": 1,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 11.3,
          "wettest_day_date": "2026-07-25",
          "longest_dry_spell_days": 24,
          "longest_dry_spell_start": "2026-07-01",
          "longest_dry_spell_end": "2026-07-24",
          "wind_gust_max_kmh": 55.0,
          "wind_gust_max_date": "2026-07-11",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 26,
          "estimated_hot_sequence_episodes": 2,
          "longest_hot_sequence_days": 23,
          "hot_sequences": [
            {
              "start": "2026-07-02",
              "end": "2026-07-24",
              "days": 23,
              "max_tx_c": 40.3
            },
            {
              "start": "2026-07-28",
              "end": "2026-07-30",
              "days": 3,
              "max_tx_c": 41.5
            }
          ]
        },
        {
          "year": null,
          "month": 8,
          "label": "Août",
          "filled_days": 31,
          "expected_days": 31,
          "coverage_percent": 100.0,
          "avg_tx_c": 33.8,
          "avg_tn_c": 19.2,
          "avg_tm_c": 25.9,
          "max_tx_c": 39.9,
          "max_tx_date": "2026-08-09",
          "min_tn_c": 14.1,
          "min_tn_date": "2026-08-22",
          "hot_days_30": 23,
          "very_hot_days_35": 13,
          "tropical_nights_20": 11,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 46.9,
          "rain_days_1mm": 8,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 13.0,
          "wettest_day_date": "2026-08-15",
          "longest_dry_spell_days": 5,
          "longest_dry_spell_start": "2026-08-04",
          "longest_dry_spell_end": "2026-08-08",
          "wind_gust_max_kmh": 88.0,
          "wind_gust_max_date": "2026-08-09",
          "windy_days_60kmh": 4,
          "estimated_hot_sequence_days": 20,
          "estimated_hot_sequence_episodes": 2,
          "longest_hot_sequence_days": 15,
          "hot_sequences": [
            {
              "start": "2026-08-01",
              "end": "2026-08-15",
              "days": 15,
              "max_tx_c": 39.9
            },
            {
              "start": "2026-08-23",
              "end": "2026-08-27",
              "days": 5,
              "max_tx_c": 35.9
            }
          ]
        },
        {
          "year": null,
          "month": 9,
          "label": "Septembre",
          "filled_days": 26,
          "expected_days": 26,
          "coverage_percent": 100.0,
          "avg_tx_c": 30.6,
          "avg_tn_c": 13.4,
          "avg_tm_c": 21.5,
          "max_tx_c": 39.2,
          "max_tx_date": "2026-09-06",
          "min_tn_c": 8.0,
          "min_tn_date": "2026-09-10",
          "hot_days_30": 17,
          "very_hot_days_35": 3,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 5.6,
          "rain_days_1mm": 1,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": 4.6,
          "wettest_day_date": "2026-09-08",
          "longest_dry_spell_days": 18,
          "longest_dry_spell_start": "2026-09-09",
          "longest_dry_spell_end": "2026-09-26",
          "wind_gust_max_kmh": 51.0,
          "wind_gust_max_date": "2026-09-01",
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 17,
          "estimated_hot_sequence_episodes": 3,
          "longest_hot_sequence_days": 8,
          "hot_sequences": [
            {
              "start": "2026-09-01",
              "end": "2026-09-08",
              "days": 8,
              "max_tx_c": 39.2
            },
            {
              "start": "2026-09-13",
              "end": "2026-09-15",
              "days": 3,
              "max_tx_c": 35.2
            },
            {
              "start": "2026-09-20",
              "end": "2026-09-25",
              "days": 6,
              "max_tx_c": 33.1
            }
          ]
        },
        {
          "year": null,
          "month": 10,
          "label": "Octobre",
          "filled_days": 0,
          "expected_days": 0,
          "coverage_percent": 0.0,
          "avg_tx_c": null,
          "avg_tn_c": null,
          "avg_tm_c": null,
          "max_tx_c": null,
          "max_tx_date": null,
          "min_tn_c": null,
          "min_tn_date": null,
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 0.0,
          "rain_days_1mm": 0,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": null,
          "wettest_day_date": null,
          "longest_dry_spell_days": 0,
          "longest_dry_spell_start": null,
          "longest_dry_spell_end": null,
          "wind_gust_max_kmh": null,
          "wind_gust_max_date": null,
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 11,
          "label": "Novembre",
          "filled_days": 0,
          "expected_days": 0,
          "coverage_percent": 0.0,
          "avg_tx_c": null,
          "avg_tn_c": null,
          "avg_tm_c": null,
          "max_tx_c": null,
          "max_tx_date": null,
          "min_tn_c": null,
          "min_tn_date": null,
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 0.0,
          "rain_days_1mm": 0,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": null,
          "wettest_day_date": null,
          "longest_dry_spell_days": 0,
          "longest_dry_spell_start": null,
          "longest_dry_spell_end": null,
          "wind_gust_max_kmh": null,
          "wind_gust_max_date": null,
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        },
        {
          "year": null,
          "month": 12,
          "label": "Décembre",
          "filled_days": 0,
          "expected_days": 0,
          "coverage_percent": 0.0,
          "avg_tx_c": null,
          "avg_tn_c": null,
          "avg_tm_c": null,
          "max_tx_c": null,
          "max_tx_date": null,
          "min_tn_c": null,
          "min_tn_date": null,
          "hot_days_30": 0,
          "very_hot_days_35": 0,
          "tropical_nights_20": 0,
          "frost_days": 0,
          "hard_frost_days": 0,
          "ice_days": 0,
          "rain_total_mm": 0.0,
          "rain_days_1mm": 0,
          "heavy_rain_days_20mm": 0,
          "wettest_day_mm": null,
          "wettest_day_date": null,
          "longest_dry_spell_days": 0,
          "longest_dry_spell_start": null,
          "longest_dry_spell_end": null,
          "wind_gust_max_kmh": null,
          "wind_gust_max_date": null,
          "windy_days_60kmh": 0,
          "estimated_hot_sequence_days": 0,
          "estimated_hot_sequence_episodes": 0,
          "longest_hot_sequence_days": 0,
          "hot_sequences": []
        }
      ],
      "events": [
        {
          "type": "heat",
          "label": "Pic de chaleur",
          "value": "41.6 °C",
          "date": "2026-06-23"
        },
        {
          "type": "cold",
          "label": "Nuit la plus froide",
          "value": "-8.2 °C",
          "date": "2026-01-05"
        },
        {
          "type": "rain",
          "label": "Pluie la plus forte",
          "value": "42.9 mm",
          "date": "2026-05-04"
        },
        {
          "type": "dry",
          "label": "Plus longue période sèche",
          "value": "26 jours",
          "date": "2026-06-29",
          "end_date": "2026-07-24"
        },
        {
          "type": "wind",
          "label": "Rafale maximale",
          "value": "113 km/h",
          "date": "2026-02-12"
        }
      ]
    }
  ]
};
